name: app_courier_api
description: A new Flutter package project.

publish_to: 'none'

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  path: ^1.7.0

dev_dependencies:
  lint: ^1.3.0
  test: ^1.15.4
