name: app_courier_api test

on:
  push:
    branches: [master]
    paths:
      - 'app_courier_api/**'
  pull_request:
    branches: [master]
    paths:
      - 'app_courier_api/**'

jobs:
  test:
    name: dart ${{ matrix.dart_version }}

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dart_version: ['2.10']

    container:
      image:  google/dart:${{ matrix.dart_version }}

    defaults:
      run:
        working-directory: app_courier_api

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Dart version
        run: dart --version

      - name: Cache pub dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-

      - name: Download pub dependencies
        run: dart pub get

      - name: Run analyzer
        run: dart analyze

      - name: Run tests
        run: dart --enable-experiment=non-nullable test
